name: Build Electron App (Windows)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies
        run: cd clientside && npm install

      - name: Build React frontend
        run: npm run build-react

      - name: Package Electron App
        run: npm run dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@main
        with:
          name: BillingApp-Windows
          path: dist/
