name: Build Electron App (Windows)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React frontend
        run: npm run build-react

      - name: Package Electron App
        run: npm run dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BillingApp-Windows
          path: dist/
          if-no-files-found: warn
